import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveFilter from "./ui/home/activeFilter";
import Filtering from "./ui/home/filtering";
import EdelLogo from "./ui/home/logo";
import TeamsFiltering from "./ui/home/teamsFilter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialised p-6`}>{children}</body>
    </html>
  );
}
